// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'memory/memory_entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3720395251345096840),
    name: 'MemoryEntry',
    lastPropertyId: const obx_int.IdUid(9, 381061922906310988),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3083683309147125837),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2988725068519693053),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1351957932188724839),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7983259504205900269),
        name: 'sessionId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4955885141021955787),
        name: 'messageId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1300076414354908495),
        name: 'timestampMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2055052728205459968),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 4554747815171770076),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 474344334371640866),
        name: 'sourceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 381061922906310988),
        name: 'sourceId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3720395251345096840),
    lastIndexId: const obx_int.IdUid(1, 4554747815171770076),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MemoryEntry: obx_int.EntityDefinition<MemoryEntry>(
      model: _entities[0],
      toOneRelations: (MemoryEntry object) => [],
      toManyRelations: (MemoryEntry object) => {},
      getId: (MemoryEntry object) => object.id,
      setId: (MemoryEntry object, int id) {
        object.id = id;
      },
      objectToFB: (MemoryEntry object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final roleOffset = fbb.writeString(object.role);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        final sourceTypeOffset = fbb.writeString(object.sourceType);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addOffset(2, roleOffset);
        fbb.addInt64(3, object.sessionId);
        fbb.addInt64(4, object.messageId);
        fbb.addInt64(5, object.timestampMs);
        fbb.addOffset(6, embeddingOffset);
        fbb.addOffset(7, sourceTypeOffset);
        fbb.addInt64(8, object.sourceId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sessionIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final messageIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final timestampMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final sourceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final sourceIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = MemoryEntry(
          id: idParam,
          content: contentParam,
          role: roleParam,
          sessionId: sessionIdParam,
          messageId: messageIdParam,
          timestampMs: timestampMsParam,
          embedding: embeddingParam,
          sourceType: sourceTypeParam,
          sourceId: sourceIdParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MemoryEntry] entity fields to define ObjectBox queries.
class MemoryEntry_ {
  /// See [MemoryEntry.id].
  static final id = obx.QueryIntegerProperty<MemoryEntry>(
    _entities[0].properties[0],
  );

  /// See [MemoryEntry.content].
  static final content = obx.QueryStringProperty<MemoryEntry>(
    _entities[0].properties[1],
  );

  /// See [MemoryEntry.role].
  static final role = obx.QueryStringProperty<MemoryEntry>(
    _entities[0].properties[2],
  );

  /// See [MemoryEntry.sessionId].
  static final sessionId = obx.QueryIntegerProperty<MemoryEntry>(
    _entities[0].properties[3],
  );

  /// See [MemoryEntry.messageId].
  static final messageId = obx.QueryIntegerProperty<MemoryEntry>(
    _entities[0].properties[4],
  );

  /// See [MemoryEntry.timestampMs].
  static final timestampMs = obx.QueryIntegerProperty<MemoryEntry>(
    _entities[0].properties[5],
  );

  /// See [MemoryEntry.embedding].
  static final embedding = obx.QueryHnswProperty<MemoryEntry>(
    _entities[0].properties[6],
  );

  /// See [MemoryEntry.sourceType].
  static final sourceType = obx.QueryStringProperty<MemoryEntry>(
    _entities[0].properties[7],
  );

  /// See [MemoryEntry.sourceId].
  static final sourceId = obx.QueryIntegerProperty<MemoryEntry>(
    _entities[0].properties[8],
  );
}
